### ISSUE TITLE
Check for attached files when ticket is submitted to GitHub

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#10]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Tuesday Dec 08, 2015 at 00:45 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/36_

---

For any Tola.Work ticket that has an attachment, and is then sent to GitHub, add a note in the GitHub issue that there is an attachment in the Tola.Work ticket.

**Comment by dborchers** [comment]
It's working
![uploads/53e1860c-cfd1-4146-9e48-632041059147/Screen Shot 2016-03-09 at 09.41.22.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F53e1860c-cfd1-4146-9e48-632041059147%2FScreen+Shot+2016-03-09+at+09.41.22.png)
