### ISSUE TITLE
Email Notification: character issues 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#102]
The email notification is in plain text and shows double quotes as &quot

**Comment by joash** [comment]
I've made some html changes to sanitize html characters for example in comments. 
![uploads/9a67ffbd-753a-4ab8-bd8b-a5620aea67de/Screen Shot 2016-06-08 at 10.46.15 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9a67ffbd-753a-4ab8-bd8b-a5620aea67de%2FScreen+Shot+2016-06-08+at+10.46.15+AM.png)

**Comment by karrla** [comment]
Thanks for working on this. 
Could you remove the following in the email to make it clean for the user: 
1. Shorten the date time stamp to just date and simple time like 09:00 
2. _Remove:_ 
   Assigned to:
   Priority: 
   Type: 
3. Remove the footer text after the ticket URL: 
   "Remember to submit and vote on the tickets in Tola.Work …….."
4. Put the “submitted to Tola.Work…” on it’s own line; add a <br> after the Ticket # and subject.
