### ISSUE TITLE
Include link back to Tola.Work in github issue desription

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#109]
Include/append to the description, the user name and email from Tola Work of who submitted and issue or comment and a link back to the issue.

**Comment by joash** [comment]
This enhancement for linking back to tw from github can now be tested in dev.

**Comment by glind** [comment]
Is adding a link back to TolaWork a Level 2 issue?  I feel like this should be level 1

**Comment by joash** [comment]
This is level 1. Changed it back.
