### ISSUE TITLE
List of *active* users

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#112]
On the home page of Tola Work add a scrolling list of users in the far right column (currently logged in or who have logged in recently) in your country with a clickable link to see each users list of assigned tasks with in a profile page.

**Comment by karrla** [comment]
It looks like the list of users is all users who have logged in, including users who are not logged in anymore. I think we'd like to have the list be only active users.

**Comment by karrla** [comment]
The Country sorting has not been added (yet?)
