### ISSUE TITLE
Pull in TolaActivity Checklist items as Tasks

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#114]
Once Checklist items are assigned in TolaActivity, have the assigned items show up in the users task list in Tola.Work.  If a user has been added to the send to for approval of Project Initiation or Project Tracking that should show up as a task as well.  Once they have checked the item off in Checklist or the open PI or PT has been approved that should check off the item as well.  They will also need a warning that checking the item off in Tasks does not complete the task in TolaActivity and it will be updated nightly with the latest status from TA.  We will also need a cron to check status of each TA task.

**Comment by glind** [comment]
Closing this ticket, this functionality is no longer needed in TolaWork.
