### ISSUE TITLE
Pull in Wrike tasks as Tasks in Tola.Work

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#115]

**Comment by glind** [comment]
MercyCorps has an Enterprise account with Wrike.  We need to explore the API integration Mahmood has done and recreate that for pushing pulling tasks into TolaWork.  This needs to be done in a way that the integration pieces could be recreated for other task management APIs as well.

**Comment by glind** [comment]
Closing this ticket, this functionality is no longer needed in TolaWork.
