### ISSUE TITLE
Filters are not working in Tola.Work 2.0

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#129]
Just creating a ticket for this, so it can be prioritized.

**Comment by glind** [comment]
We also need it to display the active filters, and have those active filters stick when adding a new sort or changing pagination.

**Comment by glind** [comment]
The active filters are displaying now but there is no way to turn them off and the hi lights of keywords is nice but it seems to highlight the keyword "none" when there is no active search.  See comment on #122...The results are persisting now but there is no way to remove the search. We need a way to show all the current filters and searches in the header of the ticket section and then remove the ones we don't want applied to the current result set
