### ISSUE TITLE
Need ability to add (NEW) Tags in Edit view : subject edited

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#130]
Currently we don't have  a field in the Edit Ticket form to add one or more Tags to the ticket.

**Comment by karrla** [comment]
I don't see where we can add tags, except in admin. We'd like to be able to add tags while viewing more details or in the edit ticket section.

**Comment by karrla** [comment]
We want to be able to assign and add NEW tags to tickets in the edit menu
