### ISSUE TITLE
Remove the word "Help Desk" from Tola Work

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#14]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Tuesday Dec 08, 2015 at 01:11 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/40_

---

[Dashboard](http://tola.work/helpdesk/dashboard/) page > change
- Title to "Work Dashboard"
- Remove text:  "Welcome to your Helpdesk Dashboard! From here you can quickly see tickets submitted by you, tickets you are working on, and those tickets that have no owner.
- Change > "Helpdesk Summary" to "Tola Work Summary"

[New Ticket](http://tola.work/helpdesk/tickets/submit/) page
- Change Title (related to: [tola-help #31]) to: "Help us help you! Please search for your issue or request before you enter a new ticket"

All Tola.Work pages: 
Change url http://tola.work/helpdesk to http://tola.work/support/  or suggestion?

**Comment by joash** [comment]
Closing this ticket and breaking the last part of this ticket "All Tola-Work pages..." into a new ticket.

**Comment by joash** [comment]
All Tola.Work pages: 
Change url http://tola.work/helpdesk to http://tola.work/support/ or suggestion?
