### ISSUE TITLE
In Dev only: user has to enter their email when submitting a ticket, it is not auto-populating

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#144]
The email field is not auto populating for users in DEV.

![uploads/4011476a-ec42-4b77-b54b-efc4ccb9cb03/Screen Shot 2016-08-18 at 1.01.01 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4011476a-ec42-4b77-b54b-efc4ccb9cb03%2FScreen+Shot+2016-08-18+at+1.01.01+PM.png)

**Comment by odenypeter** [comment]
I think the above modal is displayed for a user who is trying to submit a ticket without logging in. (public ticket form). so they have to fill in their emails. You log in, you see an autofill for the submitter field

**Comment by karrla** [comment]
Ah, yes, that makes sense, but usually a user is redirected to the login if they try and enter a ticket and they are not logged in.(http://tola.work/accounts/login/?next=/helpdesk/tickets/submit/) 

But it looks like the /home page is available to users who are not logged in (http://tola.work/home) and therefore they can submit a ticket when not logged in.

**Comment by odenypeter** [comment]
Oohh.. Just noticed that point. A user should be redirected to login page if they try submitting a ticket without logging in. I also cnfirmed that the submitter mail was only autofilled for those users who are staff. But i fixed that to autofill even for public users.I'll take care of the redirection... Thanks
