### ISSUE TITLE
Add "send to github" and "send to slack" to Details view

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#145]
The "send to github" and "send to slack" are on the old ticket view,  
http://dev.tola.work/helpdesk/tickets/385/
Can we have them on the (dropdown) details view instead?

**Comment by joash** [comment]
The 'old' ticket view is needed as a landing page by users accessing a ticket from outside TW (github, slack etcetera) so these buttons will need to be available. I will add these buttons to the 'View More Details' section in the ticket listing page.
