### ISSUE TITLE
The public view for ticket listing to be similar in structure to the authenticated user view 

### ISSUE THREAD

**Issue by joash** [toladata/TolaWork#147]
The view for ticket listings when a user is not logged into TW displays tickets in a tabular form while when a user is logged in, it displays in the new blog-like interface. I think we need to redesign the public view for ticket listing to be like the listing when a user is signed in.

**Comment by joash** [comment]
![uploads/96294036-ce5e-4f71-a721-54ad5e3c1102/helpdesk_all_tickets.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F96294036-ce5e-4f71-a721-54ad5e3c1102%2Fhelpdesk_all_tickets.png)

![uploads/137b2a79-107c-4951-9951-c3439c694e51/helpdesk_tickets.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F137b2a79-107c-4951-9951-c3439c694e51%2Fhelpdesk_tickets.png)

**Comment by odenypeter** [comment]
I think @nnie had done this. She restricted what to show for public user but on the same view

**Comment by joash** [comment]
@odenypeter, the url(r'^all_tickets/$','public_ticket_list',name='public_list') renders to 'helpdesk/public_ticket_list.html' which is a tabular template. Would you kindly check the code you have in your local instance?

**Comment by odenypeter** [comment]
Cool... In case of any adjustment, I'll check in
