### ISSUE TITLE
Link to MoreDetails of a ticket and a "Copy Ticket Link" option for users.

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#150]
Since we removed the link to the ticket (from the subject: TW ticket:#122 ), we no longer have a way to link to a ticket, since the "View more Details" does not produce a page to the ticket.

We would like the MoreDetails ticket links (http://tola.work/helpdesk/tickets/#moredetails) to actually load the "View more Details" view and "Copy Ticket Link" option for users to copy/paste the ticket link.

![uploads/aaf5e44c-88ed-4607-a916-d101f15833fe/Screen Shot 2016-08-24 at 10.31.07 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faaf5e44c-88ed-4607-a916-d101f15833fe%2FScreen+Shot+2016-08-24+at+10.31.07+AM.png)

**Comment by joash** [comment]
I think the "Copy Ticket Link" (Copy/paste link) still runs the same view (from the URL) and will still open the ticket page but shall involve additional steps for users to copy/paste than just clicking on the subject link. I think we can Then retain both (Ticket link in title and copy ticket link button ) and keep on collecting/analyzing data on how our users access the interface.
