### ISSUE TITLE
Create a separate form for "Funding Opportunities"

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#151]
Add a link on the home page for a form (similar to "Submit a Ticket") but for the "Funding Opportunities" queue. 

Form Fields: 
Name 
Contact Info (phone or email)
Short Description of Project
Anticipated Start Date of Project
Total Estimated Amount
Additional Comments

Form could be saved in it's own Model object and send a notification to Admins via Email that a new submission has been received with the details of the Form submission in the Email.  Model should be added to Admin but we do not need list or detail view in main application.

**Comment by glind** [comment]
Can we rename this, at least the button on the home page to "Get a Project Quote" and on the Form add a description at the top: "Please describe your project in detail and someone from the TolaData team will get back to you with a quote on how long it would take us to complete and when we could get started."

**Comment by karrla** [comment]
Agreed, please rename.
