### ISSUE TITLE
The "+ New Ticket" link in the top menu is broken

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#153]
The "+ New Ticket" link in the top menu is broken (in Dev for Users, but not for Admins)
link: http://dev.tola.work/helpdesk/tickets/submit/

It should load the "Submit a Ticket" modal instead

**Comment by karrla** [comment]
This is still causing an error, but only with specific "Default sort" set.  If no default sort is set, then the user will get an error. Either way, the "+ New Ticket" link should load the "Submit a Ticket" modal instead.

oReverseMatch at /helpdesk/tickets/submit/
Reverse for 'public_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method: GET
Request URL:    http://dev.tola.work/helpdesk/tickets/submit/
Django Version: 1.8.2
Exception Type: NoReverseMatch
Exception Value:  
Reverse for 'public_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location: /usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 496

**Comment by odenypeter** [comment]
I don't think the changes have reflected in dev... I removed the 'public_list' url. We no longer have it. The fixes are still in tasks2.0. Once @joash moves the changes to dev. It will be okay.

**Comment by joash** [comment]
Updated dev with tasks2.0
