### ISSUE TITLE
When submitting a new ticket, there are traces from the user's previously edited ticket

### ISSUE THREAD

**Issue by andrewtpham** [toladata/TolaWork#155]
The "Summary of the problem" field is populated with values from the previously edited ticket. See attached.
<img width="908" alt="screen shot 2016-08-29 at 11 20 15 am" src="https://cloud.githubusercontent.com/assets/4407063/18045280/ca258050-6dda-11e6-9b15-8253e669cf1b.png">

**Comment by joash** [comment]
Not sure if this is a browser's form auto fill but I was unable to get a previous entry to be available to re-use. I know Safari browser does this autofill and you might need to check Safari--Preferences--Autofill and under 'Other forms' Edit button, you check if .tola.work is one of those websites whose forms will be auto filled with previous entries.

**Comment by karrla** [comment]
I have found if the ticket is filled out and not submitted, but the modal is closed, the form will retain the data in the fields until it is deleted by the user or if the ticket is successfully submitted.
