### ISSUE TITLE
Change background color of tickets in Tickets list view to match the color of the application

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#157]
TolaActivity Queue tickets in the list view should have a background color in the panel-heading that matches the head background color of the application.  TolaTables the same.  All other Queues should be the light grey that's in the panel footer panel-heading

**Comment by karrla** [comment]
@gichiraanne loving the new queue colors! Can you make the TolaActivity Queue the orange color and the Program Management queue the white or some other color?

**Comment by gichiraanne** [comment]
Which queue is project management? Is it new?

**Comment by karrla** [comment]
PM is one of the current queues. Not sure how you decided which background colors for each queue, but the blue makes sense for TolaTables (TT) tickets and the TolaActivity (TA) should be orange

From the screenshot you can see TT is blue, TA is white and PM is orange. We'd like TA to be orange. 

![screen shot 2016-10-13 at 10 31 59 pm](https://cloud.githubusercontent.com/assets/15875770/19376690/fa69b0b4-9194-11e6-9cb2-4499b5c70430.png)

**Comment by gichiraanne** [comment]
I now get it. Seems like the ids of the queues in my local database are different from those on the server thus interchanging the two queues. let me fix that.
