### ISSUE TITLE
TW search field seems to be providing mixed search results

### ISSUE THREAD

**Issue by andrewtpham** [toladata/TolaWork#158]
This is a more general enhancement ticket. Ever since the release of TW 2.0, the search function seems to provide very different search results than before. For example, I used to be able to search by a ticket number like TT-123 or even some key words like "table" and "column" and find all the search results with those key words found in the ticket name. In the meantime, I'm happy to go to github for my ticket searches but our field users are beginning to find it frustrating to follow up on a ticket.

**Comment by joash** [comment]
You can now search by Ticket Number/ID in Dev. Not yet in production. Working on getting the irregular search addressed.
