### ISSUE TITLE
We'd like the "View Ticket in GitHub" to open in a new tab.

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#163]

**Comment by gichiraanne** [comment]
Can't seem to find this link on either the ticket list page or the individual ticket page. Where is it?

**Comment by karrla** [comment]
It is in the " View More Details" view (next to the Add to Slack button) for tickets that have been sent to GitHub, but only Admins see the link/button. Regular users will not see it.

**Comment by karrla** [comment]
The link to GitHub is still opening in the same tab, in the dev.tola.work environment, can it open in a new Tab instead?
