### ISSUE TITLE
http://tola.work/githubSync - timing out. 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#164]
loads: 

504 Gateway Time-out

nginx/1.4.6 (Ubuntu)

**Comment by odenypeter** [comment]
I think this issue should be addressed at the server settings level.... Something like these parameters setting should fix this.
add the following lines to /etc/ninx/nginx.conf (the time values can be adjusted to more favorable values)
http {
.......  
proxy_connect_timeout   15;
proxy_send_timeout      20;
proxy_read_timeout      25;
.......
}
@glind, please check that out
