### ISSUE TITLE
Add ability to add inline images ticket and comments

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#173]
Add ability to add inline images ticket and comments, this can be similar to the Huboard (see image) or GitHub  experience or it can be as simple as the user being able to paste the image inline with their text (HTML messaging).

![uploads/7cd67678-924a-45e0-a7c3-49c438c16ee8/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7cd67678-924a-45e0-a7c3-49c438c16ee8%2Fblob)

**Comment by odenypeter** [comment]
We decided to avoid inline images, but instead allow users to attach images by either selecting, drag and drop or copy pasting.

**Comment by karrla** [comment]
I like it, but I would still like to keep "inline images" in the backlog for tola.work. It would be a big win.

When supporting users it really helps to be able to add images inline. Especially when giving step by step instructions. Not have inline images is probably the biggest issue I've had trying to support users with a ticketing system (that does not support images) vs. email. Users and support staff will revert to emailing the issue or support response vs using the ticketing system. 

Even communicating with the dev team, I enter a ticket in tola.work and then add images in Huboard to communicate the issue clearly. 

I can create a new ticket if that would be helpful and mark this one as done.
