### ISSUE TITLE
Funding Opportunity Form Required Fields not Marked or error message displayed

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#177]
The Funding Opportunity form doesn't make what fields are required (though some are) and there is not message to the user that they haven't filled the form out correctly when submitted without all required fields.

**Comment by karrla** [comment]
Please add a  " \* "  next to each required field and hint text somewhere saying " \* is a required field ".

**Comment by karrla** [comment]
looks good, but could you add only one "\* is a required field" to the top of the form? 
Just add it to the green box? 

![uploads/e678c78f-0f4d-4bf0-9486-d37d361f6ba0/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe678c78f-0f4d-4bf0-9486-d37d361f6ba0%2Fblob)
