### ISSUE TITLE
TolaActivity project list is pulled from toladata.io

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#178]
We need to find a way to determine where a user is coming from and what there relevant TA or TT lists are.  This should be stored in there user profile and then used to populate the TA project lists based on toladata.io or tola-activity.mercycorps.org depending on the logged in user.

**Comment by karrla** [comment]
First phase complete: Added TolaUser Tokens section to admin 

Adding additional tickets to ensure the original request is address.

**Comment by karrla** [comment]
The first phase of this is done - added TolaUser tokens. 
But we still need  an automatic way of "determine(ing) where a user is coming from and what there relevant TA or TT lists are. "

**Comment by odenypeter** [comment]
I think for this ticket, the "automatic way" part is already addressed, what is remaining is the part addressed by ticket #262. I therefore suggest that this ticket can be closed and #262 be taken up. I.e, an automatic way to Sync TolaUsers data among the various tools to automatically get the Tables and activity tokens without admin having to input these.

**Comment by glind** [comment]
Closing this ticket.  This functionality is no longer needed in TolaWork.
