### ISSUE TITLE
The Tola.Work Dev Progress/Status missing DONE and does not match Dev status in huboard/github

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#182]
In Tola.Work we see the following Dev Status
Backlog, Ready, Working and InDev
<br> <br>  <b>We are missing the "Done" status

And the tola.work dev status are not matching the dev statuses: </b>

For example: 
TolaWork [TA-712] Export Stakeholder csv file displays the ID number instead of the label values.<br>
http://tola.work/helpdesk/tickets/712/
is labeled:  Backlog 

![uploads/067cfaec-896f-4768-804b-d7cc11e66daa/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F067cfaec-896f-4768-804b-d7cc11e66daa%2Fblob)

But it is in the "In Dev" Queue in Huboard

![uploads/f1b3f4b3-6ac4-46d6-98ce-f275315997fc/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff1b3f4b3-6ac4-46d6-98ce-f275315997fc%2Fblob)

This maybe linked to https://github.com/toladata/TolaWork/issues/164

**Comment by glind** [comment]
New tickets that aren't in github yet are marked as "in developer backlog" they should be status "new/waiting for review" until they have been moved to github.

**Comment by karrla** [comment]
I would prefer that the tickets have no Dev status (blank) if they are not in GitHub. Once I review ticket I will either send it to GitHub and it will be marked in Dev backlog or I will tag it in TolaWork with a tolawork tag. @glind will that work for you?
