### ISSUE TITLE
Edit ticket button not submitting or generating error message

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#186]
http://tola.work/helpdesk/tickets/743/

When I click on the edit button I get the form to edit.  After editing I click submit and nothing happens.  No successful submission or permissions error, just nothing.

**Comment by odenypeter** [comment]
Is this in dev/production?

**Comment by karrla** [comment]
Edit ticket from ALL tickets page and this is the pop up 

![uploads/94da7bbd-25ba-4aba-b32b-1ca610b2efea/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F94da7bbd-25ba-4aba-b32b-1ca610b2efea%2Fblob)

From the Individual page, this is the popup in DEV (in Production I do not get the error.
http://dev.tola.work/helpdesk/tickets/359/

![uploads/84df6509-db4f-4e56-9e44-43cc3b2ed485/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F84df6509-db4f-4e56-9e44-43cc3b2ed485%2Fblob)

One issue is the checkbox on the first sucessful popup, if the user checks it once, they will never see a successful submission message again.
