### ISSUE TITLE
Resolved tickets should be assigned to the submitted user and QA Lead when resolved

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#19]
<a href="https://github.com/glind"><img src="https://avatars.githubusercontent.com/u/449810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glind](https://github.com/glind)**
_Monday Dec 14, 2015 at 01:52 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/45_

---

After a ticket has been resolved by a developer or lead is should be assigned back to the user who submitted and/or the QA lead (A roll we still need.)  They should be notified by email that the issue has been resolved and is available to be tested.

**Comment by joash** [comment]
For now the QA lead has been hardcoded but will be updated later when the role is created.
