### ISSUE TITLE
Task Page: Field Label: Project Agreement should be changed to Project Initiation

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#194]
![uploads/41b6c5f3-b686-4d30-a3ea-b0ace38156bf/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F41b6c5f3-b686-4d30-a3ea-b0ace38156bf%2Fblob)

**Comment by glind** [comment]
I know it's not working yet but awesome to see a start on the integration.  Just checking to make sure this filters by the users org and country as well as the appropriate TA and TT URL
