### ISSUE TITLE
Update github api integration to pull/push new comments from work to github and vice versa

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#2]
<a href="https://github.com/glind"><img src="https://avatars.githubusercontent.com/u/449810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glind](https://github.com/glind)**
_Monday Dec 07, 2015 at 21:03 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/28_

---

Comments are not being sync'd between the 2 issue tracking systems but the api supports it.

**Comment by karrla** [comment]
In addition, if comments are added to TW ticket before it is sent to GitHub, the comments should also be sent along with the original ticket.

**Comment by joash** [comment]
When a ticket is sent to GitHub, the "Send to GitHub" is replaced by a link "View in Github". This means that any additional comment can only be saved into the FollowUp database but cannot be sent to GitHub. 

Add an enhancement for an "Update GitHub" button that updates the same ticket # in GitHub.

**Comment by joash** [comment]
To-Do : Show only the latest comment in GitHub. Currently, it shows all comments for the ticket.
![uploads/de1e9abd-38e6-481e-80c3-c15463e70bff/Screen Shot 2016-03-17 at 9.29.33 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fde1e9abd-38e6-481e-80c3-c15463e70bff%2FScreen+Shot+2016-03-17+at+9.29.33+AM.png)

**Comment by joash** [comment]
Add an enhancement to the "Update Issue in GitHub" in the event that a user types in a comment and immediately posts the comment into GitHub, which essentially excludes this comment from being posted into the comments database in TW. The comment will be sent both to GitHub and the Followup table.

**Comment by karrla** [comment]
Comments in GitHub are no longer updating in the associated Tola.Work ticket
Example: 
https://github.com/toladata/TolaActivity/issues/337
http://tola.work/helpdesk/tickets/760/
