### ISSUE TITLE
Comments and ticket updates for tickets need to be emailed to submitter and to the assigned user

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#21]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Tuesday Dec 15, 2015 at 01:15 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/47_

---

When a comment is added to a ticket or the ticket state has been changed, both the assigned user and the submitter should be sent the comment via email, if it is marked public in Tola.Work.

**Comment by karrla** [comment]
Comments on user tickets are still not being sent to the user who submitted the ticket. Example: TW #376

**Comment by joash** [comment]
TODO: customize to pick comments and submit in email body

**Comment by joash** [comment]
currently only ticket submitter receives email, which goes into spam folder. add assigner user too.
