### ISSUE TITLE
Ticket errors on save, if assigned when the ticket is created. 

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#22]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Monday Jan 11, 2016 at 19:14 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/48_

---

When creating a new ticket, if you assign the ticket to someone, TW errors on save, but ticket is still created and assigned to user.

**Comment by joash** [comment]
![issue 22](https://cloud.githubusercontent.com/assets/891518/12609419/69e36376-c496-11e5-9cb6-9c048de2d132.png)

Wouldn't re-create a ticker error for issue #22, when I assigned Greg the ticket. Closed #22.
