### ISSUE TITLE
search results missing filters for status and filter truncates results.

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#221]
If a user wants to find a ticket by searching and then filter the results by status, there are issues. 

Search "Send to Slack" 
 The results page is missing the filter check boxes: 
![uploads/bae6de7e-c412-4509-9b96-b53da3f51c82/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbae6de7e-c412-4509-9b96-b53da3f51c82%2Fblob)

<hr><hr>
<br> 
It should have: 

![uploads/97e53872-0056-47dd-afff-ebf0a1fcc3c8/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F97e53872-0056-47dd-afff-ebf0a1fcc3c8%2Fblob)

**Comment by karrla** [comment]
The filters are now there, but they do not work.

**Comment by gichiraanne** [comment]
Don't seem to get what aspect of the search results default filters is not working. Kindly clarify

**Comment by karrla** [comment]
It's working now.
