### ISSUE TITLE
Continued Issue with Status of tickets & syncing. Sync only syncs if I open the Individual ticket's page

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#222]
![uploads/da31e543-4b21-4d02-ad93-61c412e98e62/Screen Shot 2017-01-26 at 10.07.22 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fda31e543-4b21-4d02-ad93-61c412e98e62%2FScreen+Shot+2017-01-26+at+10.07.22+AM.png)

This ticket is closed in GitHub w/Label "Working", but in TolaWork All Tickets Page it shows the status: <br>
Open /  Backlog.

If the ticket is in GitHub the TW status should say only one of the following: 
In DevQueue
Resolved 
or 
Closed

![uploads/8ce8c7e6-2b78-4aa3-8080-c772ba882240/Screen Shot 2017-01-26 at 10.07.17 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8ce8c7e6-2b78-4aa3-8080-c772ba882240%2FScreen+Shot+2017-01-26+at+10.07.17+AM.png)

This ticket should be:<br>
Resolved / Working 

<br>
If I click the View More Details for the Ticket, it also shows OPEN 
![uploads/54075079-91e2-489e-a3d7-5ca5b498c01a/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F54075079-91e2-489e-a3d7-5ca5b498c01a%2Fblob)

BUT if I open this ticket's individual page in TW, it shows no status in the status area (radio buttons)

![uploads/a8ca4d26-9705-44b2-854d-fef1ddb5d1ab/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa8ca4d26-9705-44b2-854d-fef1ddb5d1ab%2Fblob)

BUT once I open the individual's ticket page (helpdesk/tickets/414/) , it syncs with GitHub and closes the ticket in TW,  the individual ticket still shows no Status, but the ticket no longer shows up in the default view on the ALL tickets page (because it is closed). 
<br>

![uploads/59e2b823-3fd7-45c2-ad8a-b8744cbe162d/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F59e2b823-3fd7-45c2-ad8a-b8744cbe162d%2Fblob)

 It only shows up if I search for closed tickets and then shows the correct label from the GitHub queue
See the status is now Closed / "Working"! (yay), 

![uploads/602d1879-31b7-48d5-851d-e37000112cbd/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F602d1879-31b7-48d5-851d-e37000112cbd%2Fblob)

but the individual ticket pages now says "In Dev Queue" "Working" 

![uploads/9e8306b0-51df-4f87-88eb-8582d2975685/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9e8306b0-51df-4f87-88eb-8582d2975685%2Fblob)

**Comment by karrla** [comment]
Now the sync is now not syncing at all, even if I open the individual ticket page.

**Comment by karrla** [comment]
sync is working but I still need to open the ticket's individual page at least once before it will sync the lables

**Comment by karrla** [comment]
@odenypeter Can you prioritize this? We would like the GitHub label syncing to work without having to open the ticket to update the status.

**Comment by karrla** [comment]
It looks like the labels are updating now,  if I click the GitHub Sync button, but then I get a bunch of notifications, which isn't a huge deal, but it looks funny: 


![uploads/fa3231fc-2e5a-4daf-8dc8-39d919abe8b3/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa3231fc-2e5a-4daf-8dc8-39d919abe8b3%2Fblob)

**Comment by karrla** [comment]
Now, everytime, I open ticket now, it creates a follow-up from GitHub status



![uploads/bcbd2939-fc7e-455e-b871-459d45fdaac9/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbcbd2939-fc7e-455e-b871-459d45fdaac9%2Fblob)

**Comment by odenypeter** [comment]
This is done

**Comment by karrla** [comment]
@odenypeter the GitHub sync is still creating multiple follow-ups 



![uploads/fa90a6b5-6543-46de-82e0-002e1e74c41c/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa90a6b5-6543-46de-82e0-002e1e74c41c%2Fblob)
