### ISSUE TITLE
Load login page instead of 404 for users not logged in who try and access a ticket.

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#23]
When a user who has not authenticated goes to a page they should not be able to access, unless they are logged in and/or have permissions, they get a Whoops! page instead of a prompt to login. These users should be redirected to a login page instead. http://tola.work/accounts/login/

**Comment by joash** [comment]
I tried re-creating the 500 Server Error 'Whoops!' w/authentication. Didn't get a Whoops!. I will update the error message - make it boring(ly) wordy and then check the server log files to figure out when this error message is fired off.

**Comment by joash** [comment]
Close Issue but to re-open again.
