### ISSUE TITLE
Edit Tasks: dates fields are not saving. 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#234]
The start and due dates are not saving when I EDIT a Task.

**Comment by karrla** [comment]
Date fields are still not saving if I edit a task and now if I edit the date field reset. 

![uploads/42682420-7603-4ab4-b539-557771b1d0be/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F42682420-7603-4ab4-b539-557771b1d0be%2Fblob)



![uploads/dc8c037d-76a6-4c08-858d-cc52593a6a56/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdc8c037d-76a6-4c08-858d-cc52593a6a56%2Fblob)

**Comment by karrla** [comment]
edit dates, loads calendar, but a new date does not delete the old date


![uploads/f1cd4427-5c3f-412a-8b81-31b06eadb9d7/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff1cd4427-5c3f-412a-8b81-31b06eadb9d7%2Fblob)

**Comment by gichiraanne** [comment]
This issue is fixed
