### ISSUE TITLE
Tasks are public, but should be private by default

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#236]
If I create a task anyone who logs into TolaWork will see my tasks. Tasks should be, by default private.

**Comment by karrla** [comment]
I can still see all tasks on the Home Page.

**Comment by karrla** [comment]
and once I submit anew ticket I see ALL tasks, not just my tasks on the My Task page

**Comment by karrla** [comment]
Tasks on Home Page are still public: 

![uploads/3403a1d3-022b-43d6-b4c3-a0a34f761ef6/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3403a1d3-022b-43d6-b4c3-a0a34f761ef6%2Fblob)

**Comment by gichiraanne** [comment]
This is fixed
