### ISSUE TITLE
Add ability to link tickets to a Task

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#237]
Add the ability linking tickets to Tasks similar to how GitHub allows you to link issues to issues. 

![uploads/7972b279-d575-4063-a40f-ad329ec48607/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7972b279-d575-4063-a40f-ad329ec48607%2Fblob)

**Comment by karrla** [comment]
Tickets are being linked, but the link text is messy if a user links more than one ticket: 

![uploads/5dde0825-6af1-4c20-b0fb-395917656a82/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5dde0825-6af1-4c20-b0fb-395917656a82%2Fblob)

**Comment by odenypeter** [comment]
I think the mess in the text is now fixed

**Comment by karrla** [comment]
I moved this back to In Dev, since tickets users can't link tickets to their Tasks they can only link tickets to newly created tasks.

**Comment by karrla** [comment]
Thanks! I see this is fixed, but can you add the text below the description box? 

"Type "#" symbol to link this Task to a Ticket(s)" 

in the Edit Task Page: 



![uploads/14ae6f5c-a9e4-4a5d-b8ab-23e151a7a5e2/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F14ae6f5c-a9e4-4a5d-b8ab-23e151a7a5e2%2Fblob)

**Comment by karrla** [comment]
One more issue: 
If I link additional tickets to an *old task*, the new linked tickets do not show up on the list of linked tickets.
