### ISSUE TITLE
Tasks: Submitter and Created by should autofill

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#239]
![uploads/ca47f998-a86f-4ccf-91cd-986771a71eca/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fca47f998-a86f-4ccf-91cd-986771a71eca%2Fblob)

**Comment by karrla** [comment]
Issue: now if the user edits a task, their name is auto-filled in the Created by box

**Comment by odenypeter** [comment]
Fixed!
