### ISSUE TITLE
Remove Knowledge Base link

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#243]
Remove the Knowledge base link in the top navigation. 

![uploads/f84d087b-9ec6-40e6-b08c-adb2a7098050/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff84d087b-9ec6-40e6-b08c-adb2a7098050%2Fblob)

**Comment by odenypeter** [comment]
Also remove all functionalities?? Or just the link?
