### ISSUE TITLE
Searching tasks

### ISSUE THREAD

**Issue by odenypeter** [toladata/TolaWork#248]
Users should be able to search tasks

**Comment by karrla** [comment]
and clear the search ;)

**Comment by gichiraanne** [comment]
The clear search functionality is done

**Comment by karrla** [comment]
Looks good, thanks. Last thing,  there should be a title on the search results page, showing what the filter list is.  Example: 

4 tasks found for "test"

**Comment by karrla** [comment]
Also, the search does not include completed tickets. If I choose to search by completed nothing shows up

**Comment by karrla** [comment]
I no longer see the "clear search" for tasks and Completed Tasks are missing, I can't find them by searching and they are not listed in the default My Task page






![uploads/9533ab1e-94bf-43e4-91bc-c1ff024c03b9/searchtasks.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9533ab1e-94bf-43e4-91bc-c1ff024c03b9%2Fsearchtasks.gif)
