### ISSUE TITLE
Error:  http://tola.work/login/

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#256]
Error: if a user clicks on the Login button, not the  Login via. Google 
VariableDoesNotExist at /login/
Failed lookup for key [helper] in u'<tr><th><label for="id_username">Username:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input id="id_username" maxlength="254" name="username" type="text" /></td></tr>\n<tr><th><label for="id_password">Password:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input id="id_password" name="password" type="password" /></td></tr>'
Request Method:	POST
Request URL:	http://tola.work/login/
Django Version:	1.8.2
Exception Type:	VariableDoesNotExist
Exception Value:	
Failed lookup for key [helper] in u'<tr><th><label for="id_username">Username:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input id="id_username" maxlength="254" name="username" type="text" /></td></tr>\n<tr><th><label for="id_password">Password:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input id="id_password" name="password" type="password" /></td></tr>'
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/template/base.py in _resolve_lookup, line 839
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/django/tola-help',
 '/home/django/tola-help/tola-help',
 '/usr/local/bin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/django/tola-help/project',
 '/home/django/tola-help']
Server time:	Wed, 1 Mar 2017 09:44:34 -0800
Error during template rendering

In template /home/django/tola-help/templates/base.html, error at line 163
(Could not get exception message)
153	                            <button type="button" class="close" data-dismiss="modal">&times;</button>
154	                            <h3 class="modal-title font9">Submit a Ticket</h3>
155	                            <p class="font9">Unless otherwise stated, all fields are required. Please provide as descriptive a title and description as possible.</p>
156	                          </div>
157	                          <div class="modal-body">
158	                            <div class="alert alert-success" role="alert">
159	                              <p>'We recommend that you search if such ticket or request already exists before you enter a new ticket. Just check if a similar ticket has not been raised<br>If you have done a search, ignore this message!'</p>
160	                            </div>
161	                            <form class="form-horizontal" method='post' action='/helpdesk/tickets/submit/' enctype='multipart/form-data'  name="most" id="ticket_form">
162	                              {% load crispy_forms_tags %}
163	
                                    
      {% crispy form form.helper %}
      

      
164	                              {% comment %}{% for field in form %}
165	                                {% if field.is_hidden %}
166	                                    {{ field }}
167	                                {% else %}
168	                                  <dt>
169	                                    <label for='id_{{ field.name }}'>{% trans field.label %}</label>{% if not field.field.required %} <span class='form_optional'>{% trans "(Optional)" %}</span>{% endif %}
170	                                  </dt>
171	                                  <dd>{{ field }}</dd>
172	                                  {% if field.errors %}<dd class='error'>{{ field.errors }}</dd>{% endif %}
173	                                  {% if field.help_text %}<dd class='form_help_text'>{% trans field.help_text %}</dd>{% endif %}
I                                                                   (bit, current))  # missing attribute ...

__
839
▼ Local vars
Variable	Value
current	
<AuthenticationForm bound=True, valid=False, fields=(username;password)>
bit	
u'helper'
e	
VariableDoesNotExist()
self	
<Variable: u'form.helper'>
context	
[{'False': False, 'None': None, 'True': True}, {}, {'site_name': u'tola.work', 'site': <Site: tola.work>, 'form': <AuthenticationForm bound=True, valid=False, fields=(username;password)>, 'next': ''}]

**Comment by odenypeter** [comment]
This error appears when a user tries logging in with wrong credentials.
