### ISSUE TITLE
Add the ability for an Admin to create an "Announcements" on Home Page from the Admin console.

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#261]
Add Announcement message above or below the Tola.Work description. Add the ability to create hyperlinks in the announcements. See example image. The end result does not have to look exactly like the example. The image is just a suggested idea.

![uploads/c60870d9-7554-4d31-a70f-6d62bd0ec4ad/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc60870d9-7554-4d31-a70f-6d62bd0ec4ad%2Fblob)

**Comment by karrla** [comment]
the announcement looks good, but maybe the issue the homepage is loading really slow now. Please verify

**Comment by gichiraanne** [comment]
The slow loading of the homepage is not caused by the announcement. However @odenypeter and I are looking at it.
