### ISSUE TITLE
Update ticket links in Tasks

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#263]
Update what the users sees when a user adds a link to a ticket in a Task, currently when a user enters a "#" they see the href, example: 
<br>
 a href="/helpdesk/tickets/9/">[Ticket: 9]</a

We would instead like them to see the ticket number and name instead: <br>
[TA-9] Change "Analyses and Reporting" tab to "Analysis and Reporting" 

And the link in the Task View would look like this instead: <br>
<a href="/helpdesk/tickets/9/"> [TA-9] Change "Analyses and Reporting" tab to "Analysis and Reporting" </a>

And if the user links multiple tickets to a task they should be in an ordered or bulleted list format

**Comment by karrla** [comment]
I'm not seeing this update. The tickets are still listed as [Ticket:#]


![uploads/51c0edbd-6de6-4dfc-8789-ce8350e8a2f7/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F51c0edbd-6de6-4dfc-8789-ce8350e8a2f7%2Fimage.png)

**Comment by odenypeter** [comment]
Your browser seems to have cached the old code. Kindly close and reopen dev.tola.work. Or try it on a different browser.  Look at this (taken from dev)
![uploads/6f756ae0-f8ba-4648-ae0b-b9f126cf70d7/Screen Shot 2017-05-20 at 08.35.12.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6f756ae0-f8ba-4648-ae0b-b9f126cf70d7%2FScreen+Shot+2017-05-20+at+08.35.12.png)

**Comment by karrla** [comment]
I can see this enhancements with my old accounts, but not any of my new accounts (even if I give them admin rights)
