### ISSUE TITLE
Add Report or List for Ticket by Queue and Number of Votes

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#265]
http://tola.work/helpdesk/reports/

We'd like to know more than the top 5 enhancements that are listed on the Home Page. 
Please create a page or report that shows us the list of tickets by queue and by number votes.

**Comment by karrla** [comment]
this looks great! 
please  remove the navigation on the right for just *this new report*, since they do not work 


![uploads/f2439de0-2b60-499f-ad09-7f23a170ce96/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff2439de0-2b60-499f-ad09-7f23a170ce96%2Fimage.png)

Page not found (404)
Request Method:	GET
Request URL:	http://dev.tola.work/helpdesk/report/tickets/userpriority/

**Comment by odenypeter** [comment]
What if I make them work? Instead of removing them?

**Comment by karrla** [comment]
That is fine, which ever is less work
