### ISSUE TITLE
Extract Tasks and User Profile into separate microservices

### ISSUE THREAD

**Issue by joash** [toladata/TolaWork#266]
The idea is to break the Tasks and User Profile functionality into logically isolated microservices.

**Comment by glind** [comment]
Sort of it's more to build one microservice that manages the users and there tasks across all the apps.  So the profiles for users would be synced across all the tools and consolidated here.  What we really want is to create a separate app called TolaProfile and have it include just the user profile information, bookmarks, and tasks.  Then create an API that will sync that across all the apps.

**Comment by joash** [comment]
Aha, 'TolaProfile'. I had called the app 'authentication'. Will refactor.

**Comment by odenypeter** [comment]
I am closing this ticket since it has been chucked into smaller tickets. And @glind comment added as description to the Milestone (TolaProfile Microservice).
