### ISSUE TITLE
Closing GitHub issues no longer resolves the tickets in TW. 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#28]

**Comment by glind** [comment]
This does work but only after visiting the dashboard.

**Comment by karrla** [comment]
This is no longer working, even if you visit dashboard.
See TW326 and GitHub#105

**Comment by joash** [comment]
"It would be nice if when an issue is closed or re-opened in GitHub w/ comments, the comments and 'Status changed in github to [closed] by user [bla bla] on date [xx/xx/xxxx]' is updated in the Tickets comments database" - I'm working on this enhancement.

**Comment by karrla** [comment]
exampe: http://tola.work/helpdesk/tickets/435/  Closed in GitHub but still open in TW

**Comment by karrla** [comment]
GitHub sync is closing tickets in Tola.Work, but we want Closed GitHub tickets to be marked as Resolved in Tola.Work, not closed. Example: http://tola.work/helpdesk/tickets/545/

**Comment by karrla** [comment]
GitHub sync is closing tickets in Tola.Work, but we want Closed GitHub tickets to be marked as Resolved in Tola.Work, not closed.

**Comment by karrla** [comment]
GitHub sync is closing tickets in Tola.Work (again), we want **Closed GitHub tickets** to be marked as **Resolved** in Tola.Work, not closed.
