### ISSUE TITLE
Knowledge-base clickable links

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#3]
<a href="https://github.com/glind"><img src="https://avatars.githubusercontent.com/u/449810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glind](https://github.com/glind)**
_Monday Dec 07, 2015 at 21:10 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/29_

---

Add html entities to all articles

**Comment by karrla** [comment]
The KB looks better, thanks! But the HTML links are still static: http://tola.work/helpdesk/kb/ can we make them active links?

**Comment by karrla** [comment]
The links are still static n the "Answer" section of the KB articles. <br>
Example: <br>
This article: http://dev.tola.work/helpdesk/kb/10/<br>
http://tola.work/documentation<br>

**Comment by karrla** [comment]
almost there! They work now on the KB page:<br>
http://dev.tola.work/helpdesk/kb/<br> Thanks!<br>
But they do not work on the actual article page: <br>
http://dev.tola.work/helpdesk/kb/10/
