### ISSUE TITLE
Error page when user submits a new Ticket

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#31]
Submiting NEW ticket causes error page.

**Comment by joash** [comment]
![new_ticket_error](https://cloud.githubusercontent.com/assets/891518/12559852/493f36c2-c34c-11e5-8ed9-8a52cc5d5e67.png)

**Comment by joash** [comment]
Looking into that.

**Comment by joash** [comment]
Same Error as #31 when Deleting ticket.  The method_decorator(staff_member_required) throwing exception w/ticket delete. Solved.
