### ISSUE TITLE
User's can't used saved queries

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#37]
If a user tries to use one of the save queries in the [Ticket view](http://tola.work/helpdesk/all_tickets/) they are prompted to log in. When they log in, the login page just reloads.

**Comment by CarolOwiti** [comment]
I tried to reproduce this login prompt for a limited user, but I was unable. I will close the ticket for now

**Comment by karrla** [comment]
This is still an issue. If I log in via Google (non-admin user), Go to Tickets, and choose a "Saved Query" from the drop down, I am prompted to log in again.
