### ISSUE TITLE
New Ticket Notification (1) Slack #tola-work channel (2) Email notification  

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#38]
It would be nice to be able to turn on notifications for Tola.Work tickets so that we can monitor for critical issues without having to log in an sort for new tickets.

**Comment by karrla** [comment]
a notification of new tickets in a new channel in tola.slack would be great! - This is done @Joash.

**Comment by glind** [comment]
Email notification is also a priority.  I have tested it on the production server and it looks to be a code issue.  We may need to debug on a local server using the file base email back in. 
 EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = '/tmp/tola-messages' # change this to a proper location

**Comment by joash** [comment]
I used EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' and it worked on local server.
