### ISSUE TITLE
Add the ability to tag tickets

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#4]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Monday Dec 07, 2015 at 23:53 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/30_

---

Add the ability to add and update (free form) tags in all tickets
Examples: 
- dig
- pm@mc
- guide_change
- form_change

**Comment by karrla** [comment]
and we'll need to be able to search and sort by the tags
