### ISSUE TITLE
Make slack integration work 

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#41]
Create a channel for Tola Work tickets in Slack add make the send to Slack button work for that

**Comment by karrla** [comment]
Once ticket is sent to slack, create a link to that conversation/channel on the ticket, similar to the "View Issue in GitHub" link

**Comment by joash** [comment]
Also, once a ticket has been posted on slack - once - it shouldn't be posted again - multiple times - (limit users from posting the same ticket many times), unless its been edited or comments added.

**Comment by joash** [comment]
When a new ticket is created, it 'auto-magically' gets posted to #tola-work channel of Tola and an 'Add to Slack' button is added to a ticket. A user can deliberately then post this new ticket to #tola-work channel of Tola Users by tapping on the 'Add to slack' button, which after sending the ticket notification, changes into 'Posted to slack' button. The user cannot then post the ticket multiple times to slack.

**Comment by karrla** [comment]
Submitting ticket no longer sends to TolaData.slack
