### ISSUE TITLE
Edit comments/history

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#43]
add ability to edit/delete comments in admin section

**Comment by Erbsenklemmer** [comment]
Hallo
`code1`

**Comment by faithnekesa** [comment]
In the Follow-up admin section where comments are edited/deleted, I changed the view to show the Ticket Title and Ticket # in square brackets followed by the comment. See the screen-shot below.
![followup_screenshot](https://cloud.githubusercontent.com/assets/16651666/13397073/3e0c30e2-df09-11e5-8378-ba0255044de8.png)
 attached

**Comment by karrla** [comment]
I can delete and edit comments, but the changes do not show up in the ticket view.

**Comment by faithnekesa** [comment]
Hi Karrla. Let me send a screen-shot of the ticket view before deletion, the actual deletion and lastly one reflecting the deletion. Then you could possibly share with me your error.
![commentsscreen1](https://cloud.githubusercontent.com/assets/16651666/13487205/16da54d2-e129-11e5-85d8-333fc11b38f9.png)
![deleting comment](https://cloud.githubusercontent.com/assets/16651666/13487210/1fcc3aec-e129-11e5-83cb-64442c550cbe.png)
![commentsecreen2](https://cloud.githubusercontent.com/assets/16651666/13487215/24e330bc-e129-11e5-81f4-e73af87f43c6.png)

**Comment by karrla** [comment]
Thanks! I was deleting the comments in the Ticket > Edit section not in the admin. It would be nice to just delete them in the Ticket > Edit, but this will work too since I doubt that we'll need to edit them very often.

**Comment by joash** [comment]
Karrla, I added a temporal redundant column 'comments' in Tickets for testing some feature/chasing a bug. That is the reason you were able to see comments when you were editing a ticket. However, comments are stored in FollowUps and the Ticket>Edit section won't show them up for now. We will need an admin to delete them up. I've updated the Tickets table appropriately.
