### ISSUE TITLE
Error if user clicks "All Ticket" view and if they try to "Search"

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#45]
If you are logged in as a regular user\* (not admin) and you click on the "Tickets" link it loads http://tola.work/helpdesk/all_tickets/  which brings up the 
"Sorry...there is a problem. 
It's not you...
It is an internal server problem."

The same error happens if you try and Search.

**Comment by joash** [comment]
Karrla, I hope this fixes the bug on ticket view and search for non-admin users. I have pushed the changes into github.
![uploads/e30e0ebf-e68b-42d4-8dd3-c1b13effcc8c/limited_user_view.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe30e0ebf-e68b-42d4-8dd3-c1b13effcc8c%2Flimited_user_view.png)
