### ISSUE TITLE
Add a "request to be added to the Ona enterprise account" form someplace in Tola Work that can then be reused on any of the tools.

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#50]
Mercy Corps has an enterprise agreement with Ona, as I suppose other organizations do as well.  We need to create a form that allows users to submit there Ona account username or email address to us so that we can forward it on to Ona to merge that account into the enterprise group.  

For now that should just be an email that is sent to tola@mercycorps.org with the username and or email and the organization name (MercyCorps) they wish to be added to.

**Comment by karrla** [comment]
Add Form that the user can request to be added to the Ona Enterprise account, gather username, email address and their existing Ona Account or if they need a new account.

**Comment by karrla** [comment]
The current plan, for Mercy Corps users, is to use this Google Form -  https://docs.google.com/a/mercycorps.org/forms/d/1dhhDPNgr7a8gEBI9U1dr_b61v6rlOP5ca3e2g6Box_g/edit?usp=drive_web

**Comment by karrla** [comment]
Thanks for updating... could you update the wording to: <br>
Title: [ONA](https://ona.io/)<br> 

Start using [Ona ](https://ona.io/home/) and easily collect and understand data from the field. 
Already using Ona? Would you and your team like to be added to enterprise account? <br>
Just fill out [this form](https://docs.google.com/forms/d/1dhhDPNgr7a8gEBI9U1dr_b61v6rlOP5ca3e2g6Box_g/viewform?edit_requested=true) and your Ona account will be added to one of our enterprise organizations. After your account has been added to an organziation, any project you create in your organization will have access to the enterprise features in Ona.
<br>
