### ISSUE TITLE
Search box on the KB page should search KB not Tickets

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#6]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Tuesday Dec 08, 2015 at 00:25 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/32_

---

Change search box on [Knowledge Base](http://tola.work/helpdesk/kb/) page so that it searches KB articles not tickets

**Comment by joash** [comment]
The Knowledge Category Search still links to the default ticket search page. 

![uploads/1c517dee-b102-472b-9f11-f26909a84144/kb_category_search.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1c517dee-b102-472b-9f11-f26909a84144%2Fkb_category_search.png)

**Comment by dborchers** [comment]
It's working
![uploads/093f875e-528b-48fb-b644-f39d8314ca9d/Screen Shot 2016-03-09 at 09.40.43.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F093f875e-528b-48fb-b644-f39d8314ca9d%2FScreen+Shot+2016-03-09+at+09.40.43.png)
