### ISSUE TITLE
"Posted to Slack" image link to Tola-User Tola-Work Archive

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#65]
It would be nice if once a ticket has been posted to Slack that the "Posted to Slack Icon"<br><br>
![uploads/5a061159-cb13-4e7a-9f81-6ec7b3971a65/Screen Shot 2016-04-13 at 11.13.56 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5a061159-cb13-4e7a-9f81-6ec7b3971a65%2FScreen+Shot+2016-04-13+at+11.13.56+AM.png)
<br> <br>Linked to the Slack Community Tola Work channel:<br>
https://tola-users.slack.com/archives/tola-work/

**Comment by joash** [comment]
"Like in GitHub, would it be possible to link tickets to their specific articles on slack channels instead of having to scroll through the entire tola-work channel looking to the ticket?" - I am looking into this slack enhancement.
