### ISSUE TITLE
The footer on the home page is cut off on the left

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#66]
The footer on the home page is cut off on the left, it should go all the way across the browser window.

**Comment by joash** [comment]
Footer is now cut on the right.
![uploads/d093445f-8636-4f7e-b1af-cf8fbeb64f54/Screen Shot 2016-04-16 at 10.24.29 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd093445f-8636-4f7e-b1af-cf8fbeb64f54%2FScreen+Shot+2016-04-16+at+10.24.29+AM.png)
