### ISSUE TITLE
Splash page Cleanup

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#69]
- Footer bar needs to stretch across the screen, currently starts slightly to the right
- Slow down slide show and limit images - Let's limit to just 3 slide show images for now and have it rotate every 15 seconds.
- Splash page should only appear when user is not logged in, after a user is logged in browsing to http://tola.work should redirect them to http://tola.work/home
- link "more information" to www.toladata.com
- Darken the background around the descriptive text for each tool (a bit hard to read on some lighter slides).  Replace text for each tool with the toppling text for each tool from toladata.com

**Comment by karrla** [comment]
Please change the text in the top right so that it is not BOLD
