### ISSUE TITLE
Error when I try to open any ticket that has been sent to GitHub. 

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#76]
Example: http://tola.work/helpdesk/tickets/331/

**Comment by karrla** [comment]
error on dev: <br>
TypeError at /helpdesk/tickets/358/ <br>
'NoneType' object has no attribute '**getitem**'<br>
Request Method: GET<br>
Request URL:    http://dev.tola.work/helpdesk/tickets/358/<br>
Django Version: 1.8.2<br>
Exception Type: TypeError<br>
Exception Value:    <br>
'NoneType' object has no attribute '**getitem**'<br>
Exception Location: /home/django/tola-help/helpdesk/github.py in get_issue_status, line 23<br>

**Comment by karrla** [comment]
Also if I send a ticket to GitHub, it gets to created in GitHub, but I get an error after submitting it.

**Comment by joash** [comment]
Test if you this error still occurs in dev - Request URL: http://dev.tola.work/helpdesk/tickets/358/

![uploads/daedd91b-7cdd-497e-9451-566dccb1b7cb/Screen Shot 2016-04-27 at 10.36.19 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdaedd91b-7cdd-497e-9451-566dccb1b7cb%2FScreen+Shot+2016-04-27+at+10.36.19+AM.png)
