### ISSUE TITLE
Dashboard does not load

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#77]
http://tola.work/helpdesk/dashboard/

Error in Dev: 
NameError at /helpdesk/dashboard/
global name 'get_issue' is not defined
Request Method: GET
Request URL:    http://dev.tola.work/helpdesk/dashboard/
Django Version: 1.8.2
Exception Type: NameError
Exception Value:  
global name 'get_issue' is not defined
Exception Location: /home/django/tola-help/helpdesk/views/staff.py in dashboard, line 211

**Comment by joash** [comment]
Test now

**Comment by karrla** [comment]
the dashboard still errors in dev and prod. Though in prod if I reload the page after it errors, it does load. dev and prod are throwing different errors

dev: global name 'get_issue' is not defined
prod: 'unicode' object has no attribute 'id'

**Comment by joash** [comment]
fixed and checked in to dev. The function was redefined as 'get_issue_status' and not 'get_issue'.
