### ISSUE TITLE
error when I delete a ticket

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#79]
error on dev
NameError at /helpdesk/dashboard/
global name 'get_issue' is not defined
Request Method: GET
Request URL:    http://dev.tola.work/helpdesk/dashboard/
Django Version: 1.8.2
Exception Type: NameError
Exception Value:  
global name 'get_issue' is not defined
Exception Location: /home/django/tola-help/helpdesk/views/staff.py in dashboard, line 211

**Comment by joash** [comment]
Try now

**Comment by joash** [comment]
![uploads/16a5179a-3d2a-423f-8c12-bf7438050613/Screen Shot 2016-04-27 at 10.08.38 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F16a5179a-3d2a-423f-8c12-bf7438050613%2FScreen+Shot+2016-04-27+at+10.08.38+AM.png)
