### ISSUE TITLE
Update the TolaActivity and TolaTables sections on the Homepage to include user specific data.

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#88]
Use the new TolaActivity API view Peter will create to query for Recent TolaActivity Project status and display in filtered list instead of the status of the TA builds with link to site.

Use the new TolaTables API view to query for Tables owned by the logged in user and display and link those instead of the status of the TT builds.

**Comment by karrla** [comment]
Currently the links to TolaTables and TolaActivity link to dev.tola.work/home# and I'm not seeing any data. Which instance is dev pointing to?

**Comment by karrla** [comment]
Can this even be tested in Dev?

**Comment by odenypeter** [comment]
This is working for TolaActivity section in dev, it is displaying latest project initiations.

**Comment by karrla** [comment]
Verified for TolaActivity, very cool. But TolaTables are not showing up.

**Comment by karrla** [comment]
Update: 

The TA Project lists on the homepage of TW Demo and the homepage of TW Prod is showing only Projects from tola.activity.io, not Projects from the corresponding TA Demo or TA Prod.

<br> 
![uploads/c4a53158-7775-4ec9-b168-c8a62fd0fe4d/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc4a53158-7775-4ec9-b168-c8a62fd0fe4d%2Fblob)

![uploads/5760f8c6-c60e-4c27-9374-f12f906b2d1a/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5760f8c6-c60e-4c27-9374-f12f906b2d1a%2Fblob)

**Comment by karrla** [comment]
this is still only showing TA PI from activity.io not demo or production
