### ISSUE TITLE
Export current view or list of tickets 

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#9]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Tuesday Dec 08, 2015 at 00:40 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/35_

---

Add option to export list of all the tickets in your current search/view from the [Tickets](http://tola.work/helpdesk/tickets/) page or the ability to "List All" so that a user can select all and paste into a spreadsheet for auditing/management of tickets outside of Tola.Work.

**Comment by karrla** [comment]
Export is only exporting the current 20 listed.
