### ISSUE TITLE
Send Ticket to GitHub causes error.

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#97]
Success, issue sent to Github, but receive this error when sent: 

UnboundLocalError at /helpdesk/tickets/513/send_to_github/
local variable 'response' referenced before assignment
Request Method: GET
Request URL:    http://tola.work/helpdesk/tickets/513/send_to_github/
Django Version: 1.8.2
Exception Type: UnboundLocalError
Exception Value:  
local variable 'response' referenced before assignment
Exception Location: /home/django/tola-help/helpdesk/views/staff.py in send_to_github, line 282

**Comment by glind** [comment]
I now get a 404 error:

Page not found (404)
Request Method: GET
Request URL:    http://tola.work/helpdesk/tickets/send_to_github/
