### ISSUE TITLE
Ticket Pagination in Tasks2.0

### ISSUE THREAD

**Issue by joash** [toladata/TolaWork#99]
Currently the new tickets list interface displays all tickets in TW, which is quite a long list. Limit the number of tickets that can be displayed in the new tickets list interface and provide for a navigation system.

**Comment by joash** [comment]
![uploads/27cac226-2cab-4555-9f84-68e4059df92e/Screen Shot 2016-06-03 at 7.48.55 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F27cac226-2cab-4555-9f84-68e4059df92e%2FScreen+Shot+2016-06-03+at+7.48.55+PM.png)
Are we able to get a navigation like this?

**Comment by glind** [comment]
The pagination looks nice but is a bit inconsistent.  The number of pages that display vs. what actually have data doesn't always work.  Occasionally you can page into blank pages after filtering.
